name = "goblin"
race = "goblin"
cr = 0.25
xp = 50
mtype = "humanoid:goblinoid"
size = "small"
alignment = "neutral evil"
str = 8
dex = 14
con = 10
int = 10
wis = 8
cha = 8
initiative_mod = 2
ac = 15
armor = ["leather armor", "shield"]
max_hp = "2d6"
speed = 30
stealth = 6
darkvision = 60
perception = 9
languages = ["Common", "Goblin"]
notes = """
Goblins are black-hearted, gather in overwhelming numbers, and crave power,
which they abuse.
"""

[skills.nimbleescape]
name = "Nimble Escape"
description = "Take Disengage or Hide as a bonus action on each turn."

[attacks.scimitar]
weapon = "scimitar"
wtype = "melee"
attack_mod = 4
reach = 5
targets = 1
damage = "1d6+2"
damage_type = "slashing"

[attacks.shortbow]
weapon = "short bow"
wtype = "ranged"
attack_mod = 4
range = [80, 320]
targets = 1
damage = "1d6+2"
damage_type = "piercing"

